### ISSUE TITLE
Round buttons don't look nice

### ISSUE THREAD

**Issue by Eisenspalter** [mladenplavsic/css-ripple-effect#7]
Round buttons don't look nice.  Is there a solution?

**Comment by mladenplavsic** [comment]
It seems like the problem is comming from browsers ability to render animation of pseudo elements which are used to present "ripple" in combination with `border-radius: 50%` and `overflow: hidden`. Calculations and positioning are OK - you can see that by playing with animation "steps", moving ripple by changing CSS properties used in animation in dev tools.
